{
 "title": "Real Driving Emissions",
 "time": { "from": "2023-09-22T16:37:26.411Z", "to": "2023-09-22T17:07:19.875Z" },
 "panels": [
  {
   "title": "Instantaneous CO2 emissions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "g/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp_samples.timestamp as time,\n  exhausts_co2_concentration_samples.value * 0.001518 * engine_exhaust_flow_rate_samples.value / 3600 as value\nFROM exhausts_co2_concentration_samples\nJOIN engine_exhaust_flow_rate_samples ON exhausts_co2_concentration_samples.timestampID = engine_exhaust_flow_rate_samples.timestampID\nJOIN timestamp_samples ON exhausts_co2_concentration_samples.timestampID = timestamp_samples.rowID;"
    }
   ]
  },
  {
   "title": "CO2 concentration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value / 10000 as \"CO2 concentration\"\nFROM exhausts_co2_concentration_samples;"
    }
   ]
  },
  {
   "title": "Engine speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  engine_speed_samples.value\nFROM engine_speed_samples;"
    }
   ]
  },
  {
   "title": "Coolant temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value\nFROM coolant_temperature_samples;"
    }
   ]
  },
  {
   "title": "Hybrid battery SOC",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value\nFROM hybrid_battery_soc_samples;"
    }
   ]
  },
  {
   "title": "Drive mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value\nFROM ev_mode_status_samples;"
    }
   ]
  },
  {
   "title": "Mileage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "miles" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value\nFROM total_distance_travelled_samples;"
    }
   ]
  },
  {
   "title": "Accelerator pedal",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value\nFROM accelerator_position_samples;"
    }
   ]
  },
  {
   "title": "Vehicle speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value\nFROM vehicle_speed_samples;"
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value\nFROM deceleration_sensor_samples;"
    }
   ]
  },
  {
   "title": "Engine status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value\nFROM engine_mode_samples;"
    }
   ]
  },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  latitude as \"latitude\",\n  longitude as \"longitude\",\n  altitude as \"altitude\"\nFROM location_samples;"
    }
   ]
  }
 ]
}